apiVersion: v2
name: weatherapp-chart
description: Chart for deploying my weather application in K8S cluster 
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
- email: tomeriko01012001@gmail.com
  name: Tomer Gabay