apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewogICAgICAgICJhdXRoIjogImRHOXRaWEpwYTI4d01UQXhNakF3TVVCbmJXRnBiQzVqYjIwNmJtOTViMjR4TXpReSIKICAgICAgfQogICAgfQogIH0KICA=